### ISSUE TITLE
ui5 build --all intermittently UPPERCASING part of the path in dist

### ISSUE THREAD

**Issue by srenwickblum** [SAP/ui5-builder#170] opened 2019-02-06 09:37 UTC
## Expected Behaviour
I expect the same folder structure found in source, to appear in the dist folder.

## Current Behaviour
![image](https://user-images.githubusercontent.com/36000044/52331983-c201bc80-29f9-11e9-81ee-fae44c265ee7.png)
As you can see above, the structure "com.test.mylib" in src changes to "com.TEST.mylib" in dist. 
I have noticed, this doesn't happen every time. When the project is too small, it happens less often, which is why I created the App.js multiple times - make it easier to reproduce.
_Note, I deleted a lot of files from dist (after the build completed) to make the screenshot more readable._

## Steps to reproduce the issue
[com.test.mylib.zip](https://github.com/SAP/ui5-builder/files/2835648/com.test.mylib.zip)
1. Unzip the attached example project
2. run npm update
3. run ui5 build --all

## Context
* UI5 Module Version 1.0.1 (globally installed)
* Node.js Version: `{v8.9.4}`
* npm Version: `{5.6.0}`
* OS/Platform: {Windows 10}

* Browser _(if relevant)_: {n/a}
* Other information: {...}

## Affected components *(if known)*
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
output looks perfect

**Comment by codeworrior** [comment] 2019-02-06 09:53
I did a quick check with 5 iterations, but couldn't reproduce the problem. Maybe because I'm running on macOS. We'll check on Windows 10 as well.

**Comment by srenwickblum** [comment] 2019-02-06 09:56
I wondered that too. Its very very odd. Its not just restricted to our project, this is also happening in sap code too. 
![image](https://user-images.githubusercontent.com/36000044/52333529-c6c86f80-29fd-11e9-8979-57b326e680e0.png)

**Comment by RandomByte** [comment] 2019-02-06 10:58
Could you please try again with UI5 CLI `v1.1.0` (released just yesterday)?  
`npm install --global @ui5/cli`

**Comment by srenwickblum** [comment] 2019-02-06 11:43
You really got my hopes up there :-)
![image](https://user-images.githubusercontent.com/36000044/52339203-bd92cf00-2a0c-11e9-9983-ead94b9c6a9c.png)
unfortunately I'm still seeing the same issue.

**Comment by srenwickblum** [comment] 2019-02-06 12:27
I just updated my NodeJS and this time (first time I've noticed it) my project was ok, but sap.f.semantic was uppercased. 
* UI5 Module Version 1.1.0 (globally installed)
* Node.js Version: `{v10.15.1}`
* npm Version: `{ 6.4.1}`
* OS/Platform: {Windows 10}

![image](https://user-images.githubusercontent.com/36000044/52341301-7f98a980-2a12-11e9-93b4-70ed34f9468a.png)

**Comment by codeworrior** [comment] 2019-02-06 12:46
I searched the web a bit and found https://nodejs.org/en/docs/guides/working-with-different-filesystems/#case-preservation as well as https://superuser.com/questions/1297658/folder-names-become-uppercase-when-syncing-to-fat32-drive . 

While the second link discusses a general issue with Win 10 and FAT32 file systems, it a) only applies to certain file name lengths and CHANGEHANDLER is too long and b) it should ALWAYS occur, not only depending on the project size.

The description behind the first link is a bit fuzzy as it doesn't name any file systems. But I would assume that it refers to the same 8.3 issue on Windows (and maybe others).

Anyhow, this doesn't give a clue what's going wrong in your case :-(

**Comment by srenwickblum** [comment] 2019-02-06 12:56
You've no idea how much I wish we were allowed to use MacOS or Linux!!! 
Those articles really sound like that is exactly the problem, but my file system is NTFS.

**Comment by RandomByte** [comment] 2019-02-06 15:05
I tried this in a Windows 10 virtual machine and apparently couldn't reproduce it.

Would you mind sharing the console output of `ui5 build --all --verbose`?

**Comment by srenwickblum** [comment] 2019-02-06 16:07
I can no longer reproduce this. I have updated my windows machine to [1809 ](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809) and it seems to have cured this issue. I'm still very very suspicious and I will run some more tests tomorrow.
But its really looks like ui5-builder (or a library it uses) isn't doing anything to cause this.

**Comment by RandomByte** [comment] 2019-02-06 16:18
Ok, good to hear. I ran some additional tests but still could not reproduce the issue. To have this documented:

I downgraded the Node installation in my VM to the one you were using first "`v8.9.4`".

Now I got:
- Windows 10 Enterprise **17**09
- Node.js: `v8.9.4`
- npm: `5.6.0`

I executed `rm -rf dist && ui5 build --all` eight times in Git Bash and checked the directory names with `tree` in Windows CMD.

Let's close this for now. Please let us know when it happens again. A `--verbose` log output would be especially helpful 👍

**Closed by RandomByte** 2019-02-06 16:18 UTC
Labels: bug, information required
