### ISSUE TITLE
Wrong i18n encoding in component-preload after build.

### ISSUE THREAD

**Issue by suN1506** [SAP/ui5-builder#105] opened 2018-11-15 15:22 UTC
## Expected Behavior
The component-preload file gets generated with i18n-entries encoded in UTF-8.

## Current Behavior
If the i18n Resourcebundle isn't encoded in ISO-8859-1 (for example in UTF-8) the component-preload gets generated with encoding errors for special characters. This is due to [Line 447 in the Builder.js file](https://github.com/SAP/ui5-builder/blob/a43ec39eb147f52762f635efae8fcbf406b6bc16/lib/lbt/bundle/Builder.js#L447)  

## Steps to reproduce the issue
1. Use any UI5 Project with an i18n resource bundle encoded in UTF-8 and include some special characters like "ÄÖÜ" to the .properties file
2. start an build task with the CLI (for example "ui5 build --all")
3. open the generated Component-preload.js file and search for encoding errors 

## Context
- OS/Platform: platform independent
- Node.js Version: 10.11.0
- npm Version: 6.4.1

## Affected components
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by matz3** [comment] 2019-01-03 10:02
This currently works as designed. In UI5, the *.properties files must be encoded in ISO-8859-1 due to legacy reasons.
`ui5 serve` also has a special handling to set the content-type accordingly, see https://github.com/SAP/ui5-server/issues/7.

We consider improving this situation in future, maybe by providing a new format for i18n files (e.g. JSON) which will then be UTF-8 encoded. Supporting both encodings is quite hard as we can't know which encoding should be used (might be solved by configuration).

For now I'm closing this as won't fix. I would suggest to add further details to the issue referenced (https://github.com/SAP/ui5-server/issues/7) or better create an issue in [ui5-tooling](https://github.com/SAP/ui5-tooling/issues/new) for a general concept.

**Closed by matz3** 2019-01-03 10:02 UTC

**Comment by matz3** [comment] 2019-07-16 07:15
We are currently working on a concept to better handle encoding of properties files: https://github.com/SAP/ui5-tooling/pull/168

**Comment by RandomByte** [comment] 2019-08-01 09:22
With UI5 CLI [`v1.7.0`](https://github.com/SAP/ui5-cli/releases/tag/v1.7.0), you can now configure `UTF-8` as the source encoding of a projects `*.properties` files. The default stays at `ISO-8859-1`. In both cases the UI5 Tooling will escape any non-ASCII characters, so that the build result is independent from the encoding.

📖 [Documentation](https://sap.github.io/ui5-tooling/pages/Configuration/#resources-optional) (see `propertiesFileSourceEncoding`)  
🔎 [Demo](https://github.com/SAP/openui5-sample-app/pull/54)
