### ISSUE TITLE
ui5 build --exclude-task escapeNonAsciiCharacters Not Working For Preload

### ISSUE THREAD

**Issue by sebasgoldberg** [SAP/ui5-builder#323] opened 2019-09-03 21:59 UTC
## Expected Behavior
To not escape the non ascii character in the Component-preload.

## Current Behavior
Escapes the non ascii character in the Component-preload.

## Steps to reproduce the issue
1. ui5 build --exclude-task escapeNonAsciiCharacters
2. Check dist/Component-preload.js
3. The non ascii characters were escaped.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.7.0`
- Node.js Version: `v10.15.3`
- npm Version: `6.4.1`
- OS/Platform: `Windows Professional 64`
- Browser *(if relevant)*: NA
- Other information: NA

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
NA

**Comment by petermuessig** [comment] 2019-09-04 05:57
Hi @sebasgoldberg,

I made the same mistake as well. You missed to add the equals character between the argument name and the value:

Yours:
```
ui5 build --exclude-task escapeNonAsciiCharacters
```

Correct:
```
ui5 build --exclude-task=escapeNonAsciiCharacters
```

This should do the trick. The UI5 CLI is interpreting the exclude-task as one argument and not separate arguments.

HTH - if not just reopen the issue. 

BR,
Peter

**Comment by petermuessig** [comment] 2019-09-04 07:53
I just had a quick talk with @matz3 and there seems to be indeed an issue with the LBT tooling used internally for the creation of the preloads. This escaping is not controlled via the task. 

I am reopening the issue so and put it on @matz3

**Comment by RandomByte** [comment] 2019-09-04 09:06
Hi @sebasgoldberg,

Non ASCII characters are always escaped in bundles like the Component-preload. We expect this change to be a compatible for all applications.

Could you please share why you do not want this escaping?

**Comment by sebasgoldberg** [comment] 2019-09-04 13:49
Hi @RandomByte ,

After doing the build, I am uploading the content of the dist folder to a BSP in an ABAP repository of an instance of SAP Gateway.

When I access the App using the Fiori Launchpad, served from the SAP Gateway, the escaped characters are showing as other symbols.

If the non ascii characters are not escaped in the Component-preload (or in the i18n file), they are showing as expected.

But this only happens when I access the App served by SAP Gateway from the ABAP repository.

Obviously, if I use `ui5 serve`, the escaped characters are displayed as expected.

@petermuessig Please note that using --exclude-task escapeNonAsciiCharacters, the content of the i18n.properties files are note escaped, but the content of the Component-preload are escaped.

Thanks in advance.

**Comment by RandomByte** [comment] 2019-09-04 14:12
Could it be possible that your i18n file is UTF-8 encoded?

By default the tooling expects i18n files to be `ISO-8859-1` encoded, so it might misinterpret your content and use the wrong escape sequences.

See configuration option `propertiesFileSourceEncoding` here: https://sap.github.io/ui5-tooling/pages/Configuration/#resources-optional

To validate this, could you please add the following to your projects `ui5.yaml` and retry whether you still see the wrong symbols after upload to ABAP?
```yaml
resources:
  configuration:
    propertiesFileSourceEncoding: "UTF-8"
```
([example](https://github.com/SAP/openui5-sample-app/blob/master/ui5.yaml#L5-L7))

---

Anyways, this sounds very similar to https://github.com/SAP/ui5-cli/issues/230 where we suspect an issue with the generation of the manifest.json generated after upload to ABAP.

**Could you please share the manifest.json that is loaded by the browser when you open the app served by SAP Gateway?**

**Comment by codeworrior** [comment] 2019-09-04 14:36
Reg. the "manifest" theory: this would only match if the wrongly encoded characters only appear in texts that originate from the manifest.json, e.g. the application name in FLP's navigation history (the drop down in the header). Can you confirm that or do you see wrongly encoded characters in other places as well?

**Comment by sebasgoldberg** [comment] 2019-09-04 15:54
@RandomByte,

My i18n file is UTF-8 encoded, and I am already using the mentioned configuration in the ui5.yaml file (`propertiesFileSourceEncoding: "UTF-8"`).

I do not think it is a problem in the manifest.json, because if I do the build without escaping the non ascii characters, and do not use the Component-preload, then is loaded the i18n.properties (with no escapes), and it works as expected.

**Comment by sebasgoldberg** [comment] 2019-09-04 15:55
Here is the manifest content:

[manifest.zip](https://github.com/SAP/ui5-builder/files/3575416/manifest.zip)

**Comment by RandomByte** [comment] 2019-09-05 11:14
I tried to reproduce this with a UTF-8 encoded i18n file, built in WebIDE and deployed to a NW ABAP system. The unicode escape sequences in `Component-preload.js` were correct and the correct characters were displayed when opening the app served from the ABAP system.

Please understand that we would like to reproduce this issue before making any changes like offering a switch for the escaping in preload bundles. We highly suspect an issue in a different component of the stack.

Would it be possible for you to raise an SAP support incident for component CA-UI5-COR? Please refer to this issue and let our support staff know that the development support team is awaiting the incident. This way we can get access to your system and analyze the issue in detail. This would be extremely helpful.

In case you can't or won't raise an incident, could you please share more details on the issue of "escaped characters are showing as other symbols"? I.e. a screenshot and an extract of the relevant escape sequences in the `Component-preload.js` and i18n file.

Thank you for your help!

**Comment by henloh** [comment] 2019-12-04 16:04
Hello there, quite some time has passed since the last update here. Because in only started developing UI5 Local recently I ran into that issue as well. I investet arroud 2 hours with no change in outcome at all. I use a node JS (selfmade) Server with proxy, so I added a own remover for the escaped chars. What I tried:

1. was the encoding of the file. I used VS Code (Windows) and Nodepad++ to change the files. No change at all.
2. I found that ui5.yaml stuff with the utf-8 encoding (code down below)
Here I tried a lot. I had UTF-8 with and without quotes, I changed the file again and used the ISO-8859-1 encoding (now I will never forget that iso code). This a couple of times back and forth and (probably) with all possible combinations.
As this was still without any change in result I decoded the file to UTF-16. It was the first time something hat impact on the preload.js, but the ÄÖÜß still did not work.
The 3. thing I found after a bit more research was the --escape-task. Again I found some with space before the task name, some with an equal - same result. In the ui5 build process you can see which tasks are executet, and the asci task DID NOT execute in both cases. But the preload.js kept having the \\u00d6 escapes. 

package.json:
`"@ui5/cli": "^1.12.0",`

ui5.yaml:
`specVersion: '1.0'
metadata:
  name: ESSForms
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: "UTF-8"`

command (all same result):
ui5 build  --exclude-task=escapeNonAsciiCharacters
ui5 build  --exclude-task escapeNonAsciiCharacters
ui5 build  --all --exclude-task escapeNonAsciiCharacters
ui5 build  --all --exclude-task=escapeNonAsciiCharacters
![pic1](https://user-images.githubusercontent.com/56073307/70157874-9baebb00-16b6-11ea-8f30-ee712c7bb734.jpg)

My humble opinion this is a bug and worthy to be fixed. 
BTW - Workarround
`var sDirPreload = "./" + sProjname + "/dist/Component-preload.js"
var sCPre = fs.readFileSync(sDirPreload).toString()
sCPre = sCPre.replace("\\\\u00c4", "Ä")
sCPre = sCPre.replace("\\\\u00d6", "Ö")
sCPre = sCPre.replace("\\\\u00dc", "Ü")
sCPre = sCPre.replace("\\\\u00df", "ß")
sCPre = sCPre.replace("\\\\u00e4", "ä")
sCPre = sCPre.replace("\\\\u00f6", "ö")
sCPre = sCPre.replace("\\\\u00fc", "ü")
fs.writeFileSync(sDirPreload, sCPre)`

I would be happy if someone would look into that. The escape task works, but not really.

Greetings and have a nice Evening 
@petermuessig @RandomByte @codeworrior @sebasgoldberg 


PS: You know you are german when you go with your Laterne and your Laterne goes with you.

**Comment by codeworrior** [comment] 2019-12-04 16:34
@henloh: Please help me to understand: what's wrong with the escapes? \u00c4 is correct and expected for Ä when the escapeNonAsciiCharacters task is used. The same is true for the other escapes. What did you expect instead?

Or are you saying that - although the escapes are correct - the text does not appear correctly in the browser? Then I wonder what code processes the preload files underway.

**Comment by henloh** [comment] 2019-12-05 09:32
@codeworrior there sould be no escape at all. why does it escape the ascii chars in the preload.js when i dont want to? WebIDE does not escpae the chars eather. 
For example the word "gefüllt" is rendered in the WebIDE as "gefüllt"
`"org/***/myApps/***/i18n/i18n_de.properties": "title=Erzeugnisstruktur\r\nappTitleNet=Erzeugnisstrukturen\r\nappDescription=List/Detail View für Erzeugnisstrukturen\r\n\r\nFillAllFields=Alle Felder müssen befüllt sein\r\nspracheempty=Sprachfeld muss gefüllt sein\r\nListOfAllsTexts=Übersetzungen\r\`

If I build the same app local via `ui5 build --exclude-task escapeNonAsciiCharacters` then it looks like that:
`"org/**/myApps/**/i18n/i18n_de.properties":'title=Erzeugnisstruktur\r\nappTitleNet=Erzeugnisstrukturen\r\nappDescription=List/Detail View f\\u00fcr Erzeugnisstrukturen\r\n\r\nFillAllFields=Alle Felder m\\u00fcssenbef\\u00fcllt sein\r\nspracheempty=Sprachfeld muss gef\\u00fcllt sein\r\n`

**Comment by RandomByte** [comment] 2019-12-09 10:28
@henloh

> why does it escape the ascii chars in the preload.js when i dont want to? WebIDE does not escpae the chars eather.

Please see [this RFC](https://github.com/SAP/ui5-tooling/blob/master/rfcs/0007-properties-file-encoding.md#rfc-0007-properties-file-encoding) for the motivation of this feature.

SAP WebIDE always expects .properties files to be UTF-8 encoded. Since -preload.js files are also always UTF-8 encoded there is no need for escaping any characters in that world. However, you'll run into issues when deploying to a server that interprets your .properties files as being `ISO-8859-1` encoded. With the UI5 Tooling you will not have this problem.

Do you experience any issues with the escape sequences? They are not nice on the eye in the build result but should work fine in your app.

**Comment by henloh** [comment] 2019-12-09 11:50
@RandomByte 
Hello, I know that RFC, 
Im truely sorry about that and I dont know any other way to descripe that. 

I want the command `ui5 build` to create a -preload.js where "gefüllt" ist written as "gefüllt" and not "gef\\u00fcllt", and there was no combination of settings and commands for me that gave me that result. Maybe it is something on my computer with encoding or windows has the problem, I know many of you work on mac. Can anyone of you share your settings how to render the -preload.js the correct way? What are you doing? You probably have a lot more experience than I do and may have already solved it. 

As mentioned [here](https://github.com/SAP/ui5-builder/issues/323#issuecomment-561711759) I configured the ui5.yaml to utf-8. I saved all the files in UTF-8 encoding. I run no other script than `ui5 build` and I still have "gef\\u00fcllt" in my -preload.js. What else can I do, except running the --exclude-task without any change in outcome?

**Comment by RandomByte** [comment] 2019-12-09 11:59
Hey @henloh, apparently I think I'm missing your point.

As stated in my first comment on this issue https://github.com/SAP/ui5-builder/issues/323#issuecomment-527812974, non-ASCII characters are **always** escaped in bundles. There is currently no way to turn this off.

Could you please elaborate on why you do not want escape characters in your preload files so that we can discuss whether a switch for this should be added to the UI5 Tooling?

The issue reported here is more likely to be UI5 runtime related and ideally should be fixed there. However, we were not able to fully analyze the issue yet (see https://github.com/SAP/ui5-builder/issues/323#issuecomment-528316020).

**Comment by henloh** [comment] 2019-12-12 06:55
Hello @RandomByte,

we have a 7.52 Gateway with FES 4 running on it. If I deploy the -preload.js with escaped chars the launchpad utf-8 encoding cannot handle it. Then we get stuff like "WarenempfÃ¤nger" instead of "Warenempfänger" if they are escaped. I dont know how the escaping would impact other files, so only the i18n is the problem at the moment for me. 

You want me to open a feature request, or something for that switch? I would love to have that. 

And thanks a lot for your patience and great help!

**Comment by codeworrior** [comment] 2019-12-12 07:10
Hi @henloh ,

thanks for the insight. Maybe _you_ could even help _us_. This is the third time we hear about such an issue with the ASCII-encoding, but we so far haven't been able to track it down to its core reason. We couldn't find out, what software component in the whole stack (other than our ResourceBundle module) is interpreting the \unnnn escapes. All three incidents involved a NW ABAP stack, but our internal inquiries didn't lead to an explanation.

If possible, could you let us know whether the FES system is a non-unicode system? Or otherwise special? 

The whole idea of using ASCII escaping is to not get the characters touched by any software component. We are therefore highly interested in understanding where exactly this approach fails and why.

Reg. your problem with the preloads: as a temporary solution, you could exclude i18n files from the preloads. If you use a manifest-declared ResourceModel, this should add a single request only (per bundle). Not nice, only a workaround.

Thank you + Kind Regards.

**Comment by henloh** [comment] 2019-12-12 09:06
Hello @codeworrior,

our Gateway System runs on windows and is a unicode system. The settings are - as far as I know - standard. I will open an OSS ticket which is addressed to you.

**Comment by RandomByte** [comment] 2019-12-12 09:43
> Can I open an OSS ticked addressed to you?

Please do! We'd love to finally be able to reproduce this issue ourselves. Software component `CA-UI5-COR`. Feel free to refer to this GitHub issue.

Thanks!

**Comment by tobiasso85** [comment] 2019-12-16 07:17
> Here is the manifest content (loaded by the browser when I open the app served by SAP Gateway):
> 
> [manifest.zip](https://github.com/SAP/ui5-builder/files/3575416/manifest.zip)

The manifest looks fine and should be unrelated.
Could you provide the ui5.yaml, the i18n.properties file and the i18n.properties (as created for the dist) and the "i18n.properties line" in the component-preload.js ?

**Comment by RandomByte** [comment] 2020-01-22 18:42
We were finally able to reproduce and analyze this issue in a live NetWeaver system 🎉

For anyone facing this issue in an FLP on ABAP environment, please implement **SAP Note [2884219](https://launchpad.support.sap.com/#/notes/2884219)**

If you continue to experience this issue, please let us know here or by raising an OSS ticket.

**Closed by RandomByte** 2020-01-22 18:42 UTC
Labels: information required
